### ISSUE TITLE
codificar la funcion de productos en assembly

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/Balam#9]

**Comment by IsraelNicolas61** [comment]
En el siguiente se encuentra el modelo de nuestra aplicación
https://github.com/SistemasTecTlaxiaco/Balam/blob/main/assembly/model.ts

El enlace siguiente es acerca del index de la aplicación desarrollada
https://github.com/SistemasTecTlaxiaco/Balam/blob/main/assembly/model.ts

**Comment by Edwin38H** [comment]
revisado
